In [2]:
import numpy as np
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier

In [3]:
X, y = make_multilabel_classification(n_classes=3, random_state=0)

In [6]:
X

array([[3., 6., 1., ..., 1., 5., 0.],
       [3., 5., 5., ..., 1., 1., 1.],
       [3., 3., 5., ..., 0., 2., 1.],
       ...,
       [3., 7., 3., ..., 2., 4., 2.],
       [7., 2., 1., ..., 1., 1., 1.],
       [3., 5., 3., ..., 1., 2., 4.]])

In [7]:
y

array([[0, 1, 0],
       [0, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 0],
       [1, 1, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 1, 0],
       [1, 1, 1],
       [0, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [1, 1, 1],
       [0, 1, 1],
       [0, 0, 1],
       [1, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 1, 0],
       [0, 1, 1],
       [0, 0, 1],
       [1, 1, 1],
       [1, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 1],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 1],
       [0, 1, 1],
       [1, 1, 1],
       [0, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0,

In [4]:
clf = MultiOutputClassifier(KNeighborsClassifier()).fit(X, y)

In [5]:
clf.predict(X[-2:])

array([[1, 1, 0],
       [1, 1, 1]])

In [9]:
clf.get_params()

{'estimator__algorithm': 'auto',
 'estimator__leaf_size': 30,
 'estimator__metric': 'minkowski',
 'estimator__metric_params': None,
 'estimator__n_jobs': None,
 'estimator__n_neighbors': 5,
 'estimator__p': 2,
 'estimator__weights': 'uniform',
 'estimator': KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                      metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                      weights='uniform'),
 'n_jobs': None}